# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftQQMusic' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
 pod 'SnapKit', '~> 3.2.0'
  # Pods for SwiftQQMusic

  target 'SwiftQQMusicTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftQQMusicUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
